services:
  lander:
    image: landerr
    container_name: landerr
    restart: always
    ports:
      - 80:80
    volumes:
      - ./template:/usr/src/app/template
    environment:
      CONFIG: |
        site-name: Landing Page
        footer: A dockerized landing page with bootstrap framework
        links:
          - name: Service 1
            text: This is my first Service. 
            href: https://www.google.com/
          - name: Service 2
            text: My second Service. 
            href: https://reddit.com/
